### ISSUE TITLE
name: Arduino-LINT should be added in YML file  (low prio)

### ISSUE THREAD

**Issue by RobTillaart** [arduino/arduino-lint#177]
I'm adding Arduino lint to my GitHub workflows and saw something worth updating:

![image](https://user-images.githubusercontent.com/462844/119876174-e31eac00-bf27-11eb-9cdf-d63810084c8a.png)

The arduino-lint.yml file should have a name field to look better.

```yml

name: Arduino-lint

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: strict
```
